name: "Group Step Example"
description: "An example pipeline that uses group steps to organize related jobs in the Buildkite UI."
emoji: ":bowling:"
steps:
  - label: ":pipeline:"
    command: "buildkite-agent pipeline upload"
